name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
     runs-on: ubuntu-larger

    steps:
    - uses: actions/checkout@v2

    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-verison: "2.6"
        bundler-cache: true
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Test
      run: npm run test
